config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/survey'

  root                            'static_pages#survey'

  get     'pictures'          =>  'static_pages#pictures'
  get     'questions'         =>  'static_pages#questions'
  get     'followup'         =>   'static_pages#followup'
  get     'addusers'          =>  'users#add_users'

  get     'login'             =>  'sessions#new'
  post    'login'             =>  'sessions#create'
  delete  'logout'            =>  'sessions#destroy'

  post    'NextQuestion'      =>  'static_pages#next_question'
  post    'SelectionCreate'   =>  'selection#create'
  post    'SelectionDone'     =>  'selection#done'
  post    'SelectionStart'    =>  'selection#start_of_question'
  post    'SelectionEnd'      =>  'selection#end_of_question'

  resources :items
  resources :finders do
    resources :orders, only: [:new, :create, :edit, :update]
  end
  resources :users
  resources :mc_questions do
    resources :orders, only: [:new, :create, :edit, :update]
  end
  resources :mc_choices
  resources :mc_responses
  resources :orders, only: [:index]

end

app/models/order.rb
class Order < ActiveRecord::Base
  #belongs_to :question, :polymorphic => true
  belongs_to :finder, :inverse_of => :order
  belongs_to :mc_question, :inverse_of => :order

  validates_uniqueness_of :orderable

  def last_order
    Order.order(orderable: :desc).select("orderable").first.orderable
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @finders = Finder.all
    @questions = McQuestion.all
  end

  def new
    @question = finder_or_mc_question
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    set_foreign_id(@order)
    if @order.save
      flash[:sucess] = "Added Order"
      redirect_to(:back)
    else
      flash[:error] = "error"
      redirect_to(:back)
    end
  end

  def edit
    @order = Order.find(params[:id])
    @finders = Finder.all
    @questions = McQuestion.all
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:sucess] = "Added Order"
      redirect_to(:back)
    else
      flash[:error] = "error"
      redirect_to(:back)
    end
  end

  private
  def order_params
    params.require(:order).permit(:orderable, :mc_question_id, :finder_id)
  end

  def finder_or_mc_question
    if params[:finder_id]
      Finder.find(params[:finder_id])
    else
      McQuestion.find(params[:mc_question_id])
    end
  end

  def set_foreign_id(order)
    if params[:finder_id]
      order.finder = Finder.find(params[:finder_id])
    else
      order.mc_question = McQuestion.find(params[:mc_question_id])
    end
    return order
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for [@question, @order] do |f|
      = f.label :orderable
      = f.number_field :orderable, class: "form-control"

      = f.submit "Submit", class: "btn btn-primary"

app/views/orders/create.html.haml
Success

app/views/orders/index.html.haml
- @finders.each do |finder|
  - if finder.order
    = link_to finder.question, edit_finder_order_path(finder,finder.order)
    = finder.order.orderable
  - else
    = link_to finder.question, new_finder_order_path(finder)
    no order
  %br
- @questions.each do |question|
  - if question.order
    = link_to question.prompt, edit_mc_question_order_path(question,question.order)
    = question.order.orderable
  - else
    = link_to question.question, new_mc_question_order_path(question)
    no order
  %br

app/views/orders/new.html.haml
%h1 
  - @question.question
= render "form"